language: python
python:
  - "2.7"

before_install:
  pip install codecov

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests

after_success:
  codecov

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests
